
name: Publish on Github, CurseForge & Modrinth

on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Kir-Antipov/mc-publish@v3.0
        with:
          modrinth-id: FIzl2Jhk
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}

          curseforge-id: 576251
          curseforge-token: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

          github-tag: mc1.19.0-1.2.0
          github-generate-changelog: true
          github-draft: false
          github-prerelease: false
          github-commitish: dev
          github-discussion: Announcements
          github-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: build/libs/*-@(dev|sources).jar

          name: Cats Expanded 1.2.0 for Minecraft 1.19.0
          version: mc1.19.0-1.2.0
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: 1.19.0
          java: 17

          retry-attempts: 2
          retry-delay: 10000
