
name : Publish on Github, CurseForge & Modrinth


on : [ pull_request, workflow_dispatch ]


env:
    MINECRAFT_VERSION_SHORT : 1.19
    MINECRAFT_VERSION : 1.19.0
    RELEASE_NAME : Cats Expanded 1.2.1 for Minecraft 1.19.0
    JAVA_VERSION : 17
    VERSION : 1.2.1+1.19.0

    CURSEFORGE_TOKEN : ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
    MODRINTH_TOKEN : ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
    GITHUB_TOKEN : ${{ secrets.PUBLISH_GITHUB_TOKEN }}


permissions:
    contents : write


jobs:
    build:
        runs-on : ubuntu-latest
        steps:
        
            -   name : Check Environment Variables
                run : env


            -   name : Checkout Repository
                uses : actions/checkout@v3
                
                with:
                    submodules : true
                    
                    
            -   name : Move To Source Folder
                run : cd Source


            -   name : Setup Java
                uses : actions/setup-java@v2
                
                with:
                    distribution : temurin
                    java-version : 17


            -   name : Make Gradle Wrapper Executable
                run : chmod +x ./gradlew
                if : ${{ runner.os != 'Windows' }}


            -   name : Build
                run : ./gradlew clean build


            -   name : Publish (CurseForge/Modrinth)
                uses : Kir-Antipov/mc-publish@v2.1
                
                with:
                    
                    curseforge-token : "${{env.CURSEFORGE_TOKEN}}"
                    curseforge-id : 576251
                    
                    modrinth-token : "${{env.MODRINTH_TOKEN}}"
                    modrinth-id : FIzl2Jhk

                    files-primary: build/libs/!(*-@(dev|sources)).jar

                    changelog-file : ../Documentation/CHANGELOG.md
                    version-type : release
                    version : "${{env.VERSION}}"
                    name : "${{env.RELEASE_NAME}}"

                    game-versions : "${{env.MINECRAFT_VERSION_SHORT}}"
                    loaders : fabric
                    java : "${{env.JAVA_VERSION}}"

                    retry-attempts : 2
                    retry-delay : 10000


            -   name : Publish (Github)
                uses : Kir-Antipov/mc-publish@v3.0
                
                with:
                    github-token : "${{env.GITHUB_TOKEN}}"
                    github-draft : false
                    github-tag : "v${{env.VERSION}}"

                    files-secondary : build/libs/*-@(dev|sources).jar
                    files-primary : build/libs/!(*-@(dev|sources)).jar

                    changelog-file : ../Documentation/CHANGELOG.md
                    version-type : release
                    version : "${{env.VERSION}}"
                    name : "${{env.RELEASE_NAME}}"

                    game-versions : "${{env.MINECRAFT_VERSION}}"
                    loaders : fabric
                    java : "${{env.JAVA_VERSION}}"

                    retry-attempts : 2
                    retry-delay : 10000
